//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flights()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int id { get; set; }
        public string departure { get; set; }
        public string destination { get; set; }
        public int airline { get; set; }
        public int typeaircraft { get; set; }
        public int ticketprice { get; set; }
        public System.TimeSpan deptime { get; set; }
        public System.TimeSpan destime { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual Airlines Airlines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
