//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passengers
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string middlename { get; set; }
        public int gender { get; set; }
        public System.DateTime datebirthday { get; set; }
        public int state { get; set; }
        public int passport { get; set; }
    
        public virtual Gender Gender1 { get; set; }
        public virtual States States { get; set; }
    }
}
