//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string middlename { get; set; }
        public int employee { get; set; }
        public int flight { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Flights Flights { get; set; }
    }
}
